# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devclean < Formula
  desc "Intelligent, zero-footgun disk cleanup CLI for macOS developers"
  homepage "https://github.com/sebavidal10/devclean"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.2.0/devclean_0.2.0_darwin_amd64.tar.gz"
    sha256 "ad0c59160cf9908a39a872eb412f9d138a6e4829f19b5cc2b1ae05c0a48d1008"

    def install
      bin.install "devclean"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.2.0/devclean_0.2.0_darwin_arm64.tar.gz"
    sha256 "8ccda04c4f21cb35df05873f0cca7f64fc036b43a205e8ec2faec8ea57f4944d"

    def install
      bin.install "devclean"
    end
  end
end
