# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devclean < Formula
  desc "Intelligent, zero-footgun disk cleanup CLI for macOS developers"
  homepage "https://github.com/sebavidal10/devclean"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.1.0/devclean_0.1.0_darwin_amd64.tar.gz"
    sha256 "4693303fefa8b69ac82a39c10dbe5f0efa726b7154d9fd189ce1e5d63ae1c2bc"

    define_method(:install) do
      bin.install "devclean"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.1.0/devclean_0.1.0_darwin_arm64.tar.gz"
    sha256 "119c73830a1baf5c7d9f51fada6f5499f1d057e06b6d60cf99200153f84f0430"

    define_method(:install) do
      bin.install "devclean"
    end
  end
end
