# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devclean < Formula
  desc "Intelligent, zero-footgun disk cleanup CLI for macOS developers"
  homepage "https://github.com/sebavidal10/devclean"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.1.0/devclean_0.1.0_darwin_amd64.tar.gz"
    sha256 "f892ce66e9c4d101176587448a655cf466fa083214849e2b3e53ac32ac2e924a"

    define_method(:install) do
      bin.install "devclean"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sebavidal10/devclean/releases/download/v0.1.0/devclean_0.1.0_darwin_arm64.tar.gz"
    sha256 "31ae9c4af78b190fa312e6b2082243d7ed6197741145e5b80c868dc2a68f393e"

    define_method(:install) do
      bin.install "devclean"
    end
  end
end
